### ISSUE TITLE
US02 -  Eu, como usuário, desejo saber onde está tendo aglomerações para evitar esses lugares

### ISSUE THREAD

**Issue by Sabanai104** [OrcestraGamificacao/DesafioCOVID-19#2]
## Descrição da Issue
Um mapa que me indique os lugares que estão tendo aglomerações de pessoas para poder evitar essas áreas.
### Tasks: 
Todas as atividades a serem realizadas devem estar elencadas em tópicos e ao serem finalizadas devem receber um check.

- [x] Ter um mapa;
- [x] Ter áreas que indicam aglomerações de pessoas;
- [x] Expiração da aglomeração

### Critérios de aceitação

- [x] Seguir o protótipo o máximo possível;
- [x] Conseguir identificar áreas com aglomerações de pessoas;
