### ISSUE TITLE
US03 - Eu, como usuário, desejo informar onde está tendo aglomerações para poder informar as pessoas.

### ISSUE THREAD

**Issue by Sabanai104** [OrcestraGamificacao/DesafioCOVID-19#3]
## Descrição da Issue
Ser capaz de informar sobre áreas do mapa que estão com aglomeração de pessoas.
### Tasks: 
Todas as atividades a serem realizadas devem estar elencadas em tópicos e ao serem finalizadas devem receber um check.
- [x] Criar inputs do "Local" ( Bairro, Rua, Munícipio);
- [x] Criar marcações para indicar a severidade(Alta, Média, Baixa);
- [x] Botão de "submeter";

### Critérios de aceitação

- [ ] Seguir o protótipo o máximo possível;
- [ ] Ser capaz de enviar informações sobre alerta de aglomerações indicando a severidade;
