### ISSUE TITLE
US05 -  Eu, como usuário, desejo ter missões de medidas de proteção para lembrar de fazer as medidas necessárias.

### ISSUE THREAD

**Issue by Sabanai104** [OrcestraGamificacao/DesafioCOVID-19#4]
## Descrição da Issue
Missões que o usuário deve realizar que esteja relacionado com medidas protetivas contra o vírus.
A cada missão concluída o usuário ganha pontos.
### Tasks: 
Todas as atividades a serem realizadas devem estar elencadas em tópicos e ao serem finalizadas devem receber um check.
- [x] Criar card " Desafio Medidas de proteção" com descrição para que serve e os pontos por cada medida feita;
- [ ] Criar mini cards para cada medida necessária com sua devida pontuação e cor;

### Critérios de aceitação

- [ ] Seguir o protótipo o máximo possível;
- [ ] Poder o mini card marcar quando uma tarefa for realizada;
- [ ] Ganhar pontuação ao marcar o mini card;
