### ISSUE TITLE
US06 -  Eu, como usuário, desejo ter desafios de comunidade para interagir com as pessoas não presencialmente.

### ISSUE THREAD

**Issue by Sabanai104** [OrcestraGamificacao/DesafioCOVID-19#5]
## Descrição da Issue
Desafios de interação e comunicação com a comunidade com desafios separados por manhã, tarde e noite. 
### Tasks: 
Todas as atividades a serem realizadas devem estar elencadas em tópicos e ao serem finalizadas devem receber um check.
- [ ] Criar card de "Desafio Comunidade" com descrição explicando o que é e para que serve e com as devidas pontuações para cada mini card;
- [ ] Criar mini cards para os desafios divididos em manhã, tarde e noite com suas devidas pontuações e cores;

### Critérios de aceitação

- [ ] Seguir protótipo o máximo possível;
- [ ] Poder marcar um mini card quando for realizado um desafio;
- [ ] Ganhar pontuação ao marcar um mini card;
