### ISSUE TITLE
US09 -  Eu, como usuário, desejo ver de forma visual o progresso do vírus para saber como está a situação no Brasil e no Mundo.

### ISSUE THREAD

**Issue by Sabanai104** [OrcestraGamificacao/DesafioCOVID-19#6]
## Descrição da Issue

Page "progressão do coronavírus" que  mostra a quantidade de contaminados no mundo e no Brasil, para que assim, o usuário consiga acompanhar a progressão do vírus.

### Tasks: 
Todas as atividades a serem realizadas devem estar elencadas em tópicos e ao serem finalizadas devem receber um check.
- [x] Criar page "Progressão do coronavírus";
- [x] Criar parte "mundial" que mostra a imagem do vírus e a quantidade de infectados;
- [x] Criar parte "Brasil" que mostra a imagem do vírus e a quantidade de infectados no Brasil;
- [ ] Criar botão "info" que abre o texto da issue "US10";

### Critérios de aceitação

- [x] Seguir o protótipo o máximo possível;
- [x] A imagem do vírus deve crescer em proporção a quantidade de infectados;
- [ ] O texto deve aparecer quando apertar o botão "info";

**Comment by devsalula** [comment]
https://github.com/mathdroid/covid-19-api @sudjoao
