### ISSUE TITLE
US10 -  Eu, como desenvolvedor desejo conscientizar as pessoas que elas são  protagonistas para entenderem o papel delas na situação.

### ISSUE THREAD

**Issue by Sabanai104** [OrcestraGamificacao/DesafioCOVID-19#7]
## Descrição da Issue

Feature, ativada pelo botão "info", na pagina  "Progressão do coronavírus" que contem um texto para motivar e conscientizar o usuário e faze-lo perceber sua importância na crise atual. 

### Tasks: 
Todas as atividades a serem realizadas devem estar elencadas em tópicos e ao serem finalizadas devem receber um check.
- [ ] Criar o texto com imagem para motivar e conscientizar o usuário.
- [ ] Botão "info" no topo superior direito;

### Critérios de aceitação

- [ ] Seguir protótipo o máximo possível;
- [ ] Conter o texto e imagem;
- [ ] Voltar para a página "Progressão do coronavírus" ao apertar o botão "info";
