### ISSUE TITLE
US11 -  Eu, como autoridade, desejo que a pessoa informe quando sair de casa para ter um controle de saída delas.

### ISSUE THREAD

**Issue by Sabanai104** [OrcestraGamificacao/DesafioCOVID-19#9]
## Descrição da Issue
Pagina "Aviso de Saída" ao qual o usuário avisa quando for sair de casa e qual de
### Tasks: 
Todas as atividades a serem realizadas devem estar elencadas em tópicos e ao serem finalizadas devem receber um check.
- [x] Criar pagina "Aviso de Saída";
- [x] Criar um drop down "Destino" com os locais de destino que usuário pode ir (Farmácia, Mercado, Hospital);
- [x] Criar botão "Submeter";

### Critérios de aceitação

- [x] Seguir o protótipo o máximo possível;
- [x] Poder escolher entre as opções Farmácia, Mercado ou Hospital;
- [ ] A informação ser enviada pressionar o botão "Submeter";
